apiVersion: v1
kind: Service
metadata:
  name: options-backend
  labels:
    app: options-backend
spec:
  selector:
    app: options-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
